/*
 * ErrorCode.h
 *
 *  Created on: 14 lip 2021
 *      Author: DanielD
 */

#ifndef INC_ERRORCODE_H_
#define INC_ERRORCODE_H_
#include "stm32h7xx_hal.h"
#define ERROR_CODE_MAXLEN 150
/*
 * Definicje kodów błedów
 */
#define UNIMPORTANT_ERROR 250
#define HCSR04_INIT_ERROR 1
#define UARTCOM_INIT_ERROR 2
#define UARTCOM_ADDFRAME_FULL 3
#define UARTCOM_ADDFRAME_INVALID_LENGTH_FRAME 4
#define UARTCOM_ADDFRAME_NOT_EXECUTE_PREVIOUS_FUN 5
#define ERROR_ERRORCODEPUSH_FULL 6
#define VL5310X_INCORRECT_MODEL_ID 7
#define VL5310X_INCORRECT_BUDGET_US 8
#define VL5310X_INCORRECT_PERIOD_VCSELPERIODPRERANGE 9
#define VL5310X_INCORRECT_PERIOD_VCSELPERIODFINALRANGE 10
#define VL5310X_INCORRECT_TYPE_VCSELPERIODTYPE 11
#define VL5310X_TIMEOUT_READRANGECONTINUOUSMILLIMETERS 12
#define VL5310X_TIMEOUT_READRANGESINGLEMILLIMETERS 13
#define VL5310X_TIMEOUT_GETSPADINFO 14
#define VL5310X_ERROR_ENCODETIMEOUT 15
#define VL5310X_TIMEOUT_PERFORMSINGLEREFCALIBRATION 16
#define MAIN_HCSR04_GET_DISTANCE_TIMEOUT 17
#define STATEMACHINE_TIMEOUT 18
#define STATEMACHINE_GPIO_POINTER_NULL 19
#define STATEMACHINE_HTIM_POINTER_NULL 20
#define UARTCOM_HTIM_POINTER_NULL 21
#define IRSENSOR_NUMBER_OUT_OF_SIZE 22
#define IRSENSOR_GPIO_POINTER_NULL 23
#define UARTCOM_MAX_LENGTH_IR_STATUS_SEND 24
#define FLASH_BASE_STRUCT_NULL 25
#define FLASH_UNLOCK_ERROR 26
#define FLASH_ERASE_ERROR 27
#define ADC_HADC_NULL_POINTER 28
#define SERVO360_NO_NUMBER_IN_ARRAY 29
#define SERVO360_CURRENTPOSITION_OUT_OF_RANGE 30
#define VL53L0X_NULL_XSHUL_POINTER 31





typedef struct {
    uint8_t buffer[150]; //uint8_t
    int head;
    int tail;
    int maxlen;
} error_bbuf_t;


error_bbuf_t errorCode_s;

void errorCodeInit();
void errorCodePush(const uint8_t data);
uint8_t errorCodePop();


#endif /* INC_ERRORCODE_H_ */
